apiVersion: v1
dependencies:
- name: service-mesh-hub
  repository: https://storage.googleapis.com/service-mesh-hub/service-mesh-hub
  version: 0.8.1
- name: cert-agent
  repository: https://storage.googleapis.com/service-mesh-hub/cert-agent
  version: 0.8.1
- name: service-mesh-hub-ui
  repository: https://storage.googleapis.com/service-mesh-hub-enterprise/service-mesh-hub-ui
  version: 0.5.3
description: Enterprise components for Service Mesh Hub.
home: https://solo.io
name: service-mesh-hub-enterprise
version: %version%
